server:
  port: 8001

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/htrzak/MicroServices
          searchPaths: ConfigData
        # "native" is used when the native profile is active, for local test with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
